apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql-slave
spec:
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    # 对应 nfs 服务器/etc/exports 文件配置
    path: /data/mysql-slave
    # nfs 服务器IP
    server: 192.168.137.153
  persistentVolumeReclaimPolicy: Recycle


